tosca_definitions_version: tosca_simple_yaml_1_3

metadata:
  template_name: "hello-web"
  template_author: "XLAB"
  template_version: "1.0"

node_types:
  hello_type:
    derived_from: tosca.nodes.SoftwareComponent
    interfaces:
      Standard:
        inputs:
          file_contents:
            value: { get_input: hello_input }
            type: string
        operations:
          create: playbooks/create.yaml
          delete: playbooks/delete.yaml

topology_template:
  inputs:
    hello_input:
      type: string
      default: "hello web"

  node_templates:
    deploy-workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    hello:
      type: hello_type
      requirements:
        - host: deploy-workstation
