---
- hosts: all
  gather_facts: false

  tasks:
    - name: Install Apache2
      apt:
        name: apache2

    - name: Start Apache2 if not started
      ansible.builtin.service:
        name: apache2
        state: started

    - name: Deploy web page contents
      copy:
        dest: /var/www/html/index.html
        content: "{{ file_contents }}"
        backup: true
